#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

def turn_off_buddyalloc(off=True):
    with open("kernel/buddyalloc.h", "w") as f:
        if off:
            f.write("#define BUDDY_OFF\n")

@test(0, "pgtbltest")
def test_pgtbltest():
    turn_off_buddyalloc(True)
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)
   
@test(5, "answers-pgtbl.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-pgtbl.txt")
    
@test(10, "pgtbltest: ugetpid", parent=test_pgtbltest)
def test_ugetpid_():
    r.match('^ugetpid_test: OK$')

@test(10, "pgtbltest: print_kpgtbl", parent=test_pgtbltest)
def test_print_kpgtbl_():
    r.match(
        '^page table 0x',
        '^ \.\.0x0000000000000000',
        '^ \.\. \.\.0x0000000000000000',
        '^ \.\. \.\. \.\.0x0000000000000000',
        '^ \.\. \.\. \.\.0x0000000000001000',
        '^ \.\. \.\. \.\.0x0000000000002000',
        '^ \.\. \.\. \.\.0x0000000000003000',
        '^ \.\.(0xffffffffc0000000|0x0000003fc0000000)',
        '^ \.\. \.\.(0xffffffffffe00000|0x0000003fffe00000)',
        '^ \.\. \.\. \.\.(0xffffffffffffd000|0x0000003fffffd000)',
        '^ \.\. \.\. \.\.(0xffffffffffffe000|0x0000003fffffe000)',
        '^ \.\. \.\. \.\.(0xfffffffffffff000|0x0000003ffffff000)',
    )

@test(20, "pgtbltest: superpg", parent=test_pgtbltest)
def test_superpg_():
    r.match('^superpg_fork: OK$')
    r.match('^superpg_free: OK$')
    
@test(5, "pgtbl_usertests")
def test_pgtbl_usertests():
    turn_off_buddyalloc(True)
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)
    r.match('^ALL TESTS PASSED$')
    
@test(5, "buddytest: buddyalloc")
def test_buddyalloc_():
    turn_off_buddyalloc(False)
    r.run_qemu(shell_script([
        'buddytest'
    ]), timeout=300)
    r.match('^buddy_contig: OK$')
    r.match('^buddy_coalescing: OK$')
        
@test(5, "buddyalloc_usertests")
def test_buddyalloc_usertests():
    turn_off_buddyalloc(False)
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)
    r.match('^ALL TESTS PASSED$')
    
@test(1, "references.txt")
def test_references():
    check_references()
    
@test(0, "time")
def test_time():
    check_time()

run_tests()
